# Copyright 2025 New Vector Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
# Please see LICENSE files in the repository root for full details.

# Documentation for possible options in this file is at
# https://rust-lang.github.io/mdBook/format/config.html
[book]
title = "Matrix Authentication Service"
authors = ["The Matrix.org Foundation C.I.C."]
language = "en"
multilingual = false

src = "docs"

[build]
build-dir = "target/book"

[output.html]
# The URL visitors will be directed to when they try to edit a page
edit-url-template = "https://github.com/element-hq/matrix-authentication-service/edit/main/{path}"

# The source code URL of the repository
git-repository-url = "https://github.com/element-hq/matrix-authentication-service"

# The path that the docs are hosted on
site-url = "/matrix-authentication-service/"
